namespace pow.hermes
{
    public enum RewardedVideoTag
    {
        untagged,
        shop_earn_coin_rew,
        start_game_popup_use_magnet_rew,
        start_game_popup_use_extratime_rew,
        ingame_booster_popup_use_hint_rew,
        ingame_booster_popup_use_freezetime_rew,
        level_complete_popup_multiply_stars_rew,
        level_fail_popup_clean_all_slots_rew,
        level_fail_popup_times_up_extra_time_rew,
        home_life_icon_extra_life_rew,
        start_game_nolife_popup_extra_life_rew,
        level_fail_popup_nolife_retry_extra_life_rew,
        pause_popup_nolife_retry_extra_life_rew,
        level_fail_out_of_slots_popup_10_gold_rew,
        level_fail_time_is_up_popup_10_gold_rew,
        ingame_booster_popup_use_undo_rew,
        ingame_booster_popup_use_shuffle_rew,
        complete_word_multiply_gold_rew,
        star_chest_multiply_gold_rew,
        level_chest_multiply_gold_rew,
        daily_login_multiply_rewards_rew,
        fortune_path_multiply_gold_rew,
        inter_level_3x_coin_rew,
        refill_lives_rew
    }
}